apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "springeight"
  description: "this is the description"
  annotations:
    github.com/project-slug: juananmora/springeight
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: io.kompose.service=web,mysql

spec:
  type: service
  lifecycle: production
  owner: "team-a"
  dependsOn:
  - component:springfive
  - component:springfour
  - component:springseven
