apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "springeight"
  description: "this is the description"
  annotations:
    github.com/project-slug: juananmora/springeight
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=selenium-grid
    litmuschaos.io/project-id: 26e2e754-a79f-447f-a465-587f8303a373
spec:
  type: service
  lifecycle: production
  owner: "team-a"

